# Default values for sigscale-im
#
replicaCount: 1
image:
  repository: sigscale/im
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
restService:
  type: LoadBalancer
  clusterIP: ""
  port: 80
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
podResources: {}
nodeSelector: {}
tolerations: []
affinity: {}
dataVolume:
  size: 10Gi
  class: ""
logsVolume:
  size: 10Gi
  class: ""
erlangArgs: ""
imConfig:
  create: false
  sysConfig: "[]."
