{{- if .Values.imConfig.create -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-im-config
  labels:
    {{- include "sigscale-im.labels" . | nindent 4 }}
data:
  sys.config: {{ .Values.imConfig.sysConfig | quote }} 
{{- end }}
